### ISSUE TITLE
Clone of nerwork

### ISSUE THREAD

**Issue by ghost** [stuttter/wp-multi-network#114]
Hello!

There is a possibility to clone one network with all settings (settings active plugins etc.)?

**Comment by JJJ** [comment]
This did exist previously, but was slowly cut out years ago because it was never used in the UI, and it was darn-near incomplete in its implementation.

Do you want to clone all sites also, or just the main site? What/how do you want to decide the new name/path/etc... There's a lot to define. If you have suggestions, feel free to drop them here and we can talk through this as a future feature?

**Comment by AmibeWebsites** [comment]
There's an existing plugin that clones a site... I've not used it to clone a network but it may provide a good basis from which to start.

**Comment by agrajagco** [comment]
@thegronix - For moving sites and seeding development instances of new sites using same look & feel (and production release) for our hosting sites we ended up licensing (and working with to fix bugs) the All-in-One WP Migration tool with their multi-site extension, they provided updates that added support for WP multi-network import/export/backup/restore of sites. Very flexible.

**Comment by JJJ** [comment]
Gonna close this out.

If we want to bring the network clone function back, I _think_ it would be as a separate plugin.

**Comment by sharulhafiz** [comment]
> Hey, so is All In One able to clone a network (without the sites) and all of it's settings?

I'm using the plugin now, yes it can.. so far.
