### ISSUE TITLE
h5p content creation and editing not possible due to route_save_handlers () WPCS fixes in #3b732ac

### ISSUE THREAD

**Issue by richardtape** [stuttter/wp-multi-network#138]
Hey!

Prior to

https://github.com/stuttter/wp-multi-network/commit/3b732ac6a960c7279aa4afdce994170c7c4d1f72#diff-4c1ff5ed37585a283185fb4e6cd50f70R297

The h5p plugin for WordPress could create and edit existing h5p content. However, after that commit, it's now not possible. Upon saving or creating h5p content a `wp_die()` screen appears with the message `The link you followed has expired.`

Some debugging lead me to the above commit being the culprit. This is because h5p does something remarkably similar:

https://github.com/h5p/h5p-wordpress-plugin/blob/master/admin/class-h5p-content-admin.php#L345

If I comment out the `admin_init` action call at https://github.com/stuttter/wp-multi-network/blob/master/wp-multi-network/includes/classes/class-wp-ms-networks-admin.php#L41 then h5p returns to normal running mode.

I'm happy to do the leg work here and provide a PR but wanted to start an issue to help us discuss the best way forward. I can see a few ways, but my initial thought was the ensure that the `route_save_handlers()` method's code only runs on the appropriate WPMN pages. Could possibly do this by ensuring we're at the network admin level, or maybe specifically checking we're on specific screens using `get_current_screen`.

What are your thoughts here and, JJJ/Felix, thanks as always.

**Comment by felixarntz** [comment]
@richardtape Good catch. When I made these changes, I must have missed that the method is always executed regardless where you are at.

About the approach, I think I'd prefer to put an extra check into `route_save_handlers()` initially. For example, each form that submits to one of those actions could also send a `wp_multi_network=1` value over, just to identify that this action comes from WP Multi Network. I would have typically prefixed the actions themselves, but since they are not set in stone and since this is a close-to-core plugin, checking for the extra value initially and bailing if it is not present would be a good workaround IMO. Limiting it to only the WPMN pages would work too, but I think execution of such actions should not be tied to a specific screen.

**Comment by richardtape** [comment]
Thanks for the reply, @felixarntz 

Just so I'm clear, you're suggesting something like adding

`<input type="hidden" name="wp-multi-network" id="wp-multi-network" value="1">`

to each form, and then checking for that as part of the request from within `route_save_handlers()`?

**Comment by felixarntz** [comment]
@richardtape Yes, exactly that. It think that would be an acceptable workaround for the fact that the actions aren't scoped by being prefixed with `wpmn` or `wp-multi-network`.

**Comment by richardtape** [comment]
OK perfect. Thanks so much for the fast reply @felixarntz 

I'll work on that as soon as I can and get a PR in place.
