### ISSUE TITLE
Logical error on Network Edit Page

### ISSUE THREAD

**Issue by jotazzu** [stuttter/wp-multi-network#72]
As described by several users saving changes on the Network Edit Page results in all subsites orphaned which are not assigned to the currently edited network.
[WordPress › Support » When EDIT a network, its subsites become orphaned?](https://wordpress.org/support/topic/when-edit-a-network-its-subsites-become-orphaned?replies=1)
[WordPress › Support » Saving a network removes sites from other networks](https://wordpress.org/support/topic/saving-a-network-removes-sites-from-other-networks?replies=6)
[WordPress › Support » Network.zero as root domain in dashboard](https://wordpress.org/support/topic/networkzero-as-root-domain-in-dashboard?replies=6#post-8146635)
[WordPress › Support » Network Edit Screen fails with WP 4.4.1](https://wordpress.org/support/topic/network-edit-screen-fails-with-wp-441?replies=2)
[Comment on issue #63 "Failling sites on WP 4.4"](https://github.com/stuttter/wp-multi-network/issues/63#issuecomment-181355912)

The reason for this is located at the end of function reassign_sites_handler() in file includes/classes/class-wp-ms-networks-admin.php. All subsites still listet in the left select box (name="from[]") are "orphaned out" when the update is executed. 

At least it is logically not possible in that situation to distinguish which subsites in the "from" list should be orphaned and which should remain assigned to their original network.

A quick solution might be to list only orphaned subsites in the "from" list. Moving a subsite would result in two steps then. The first step is to remove subsites from it's current network and click update to get them orphaned. In the second step the edit page of the new network is called and the previously orphaned subsites can be reassigned.

**Comment by christianwach** [comment]
What [Networks-for-WordPress](https://github.com/ddean4040/Networks-for-WordPress) does is that it has a constant [`ENABLE_HOLDING_SITE`](https://github.com/ddean4040/Networks-for-WordPress/blob/master/index.php#L33-L37) which, if set to false, means that there is [no ability to "unassign" blogs without reassigning them](https://github.com/ddean4040/Networks-for-WordPress/blob/master/networks-admin.php#L723-L730). To me, this is a more flexible and robust approach. I get to choose the behaviour of the "Site Assignment" interface.

The real issue here, in my opinion, is that the "Site Assignment" interface is ambiguous. Having just "Available Sites" and "Network Sites" as options is not quite enough to carry out the intentions of network administrators. I would like to see something similar to the WordPress Widgets interface, where there is the ability to explicitly "orphan" widgets without losing their settings or content. A similar ability in this plugin's admin interface would then represent the deliberate act of orphaning a site.

In the meantime, however, [adding a filter at the appropriate point](https://github.com/stuttter/wp-multi-network/blob/master/includes/classes/class-wp-ms-networks-admin.php#L899-L903) would at least provide the same flexibility as Networks-for-WordPress:

```php
// Orphaning out
} elseif ( in_array( $site_id, $from ) && apply_filters( 'mynetworks_orphan_sites', true ) ) {
	move_site( $site_id, 0 );
}
```

This filter would probably be more appropriately placed before the foreach loop, but I presume the intent of this code is clear.

**Comment by jotazzu** [comment]
Another quick solution which preserves the option to set subsites as orphaned, changes the same code line christianwach has suggested. But instead applying a filter it checks in the database if the subsite is still assigned to the target network. 
```
// Orphaning out
} elseif ( in_array( $site_id, $from ) && in_array( $site_id, $sites ) ) {
	move_site( $site_id, 0 );
}
```

**Comment by johnjamesjacoby** [comment]
Hey everyone. What would you like to see happen here?

Would you prefer to have the ability to purposely "orphan" or "disconnect" a site from a network?

**Comment by fjarrett** [comment]
+1 for disconnecting a site from a network

**Comment by johnjamesjacoby** [comment]
The original bug was fixed a while ago, so I'm closing this and opening a new issue for the option to orphan a site from a network on purpose.
