### ISSUE TITLE
Switch `$domain` global as part of `switch_to_network()`

### ISSUE THREAD

**Issue by boonebgorges** [stuttter/wp-multi-network#96]
I'm adding a network selector to wp-signup.php (on a subdomain network), which is less easy than it sounds :-/ I can fake most things by handling the `$_POST` request inside of a `switch_to_network()` call. But `wpmu_validate_blog_signup()` builds the site domain out of the `$domain` global. 

Say I have two networks:
- `site_id = 1`, `domain = foo.example.com`
- `site_id = 2`, `domain = bar.example.com`

By switching to network 2, a new site called `baz` gets put into `site_id 2` - as expected - but ends up with the domain `baz.foo.example.com`.

I'm unsure what else the `$domain` global does, so I haven't prepared a PR.

**Comment by JJJ** [comment]
Thanks @boonebgorges. This makes sense to me.

BuddyPress, ironically, does something similar in `bp_blogs_validate_blog_signup()`.

I'll look into it.

**Comment by JJJ** [comment]
A few thoughts:

* I don't think we can switch the `$path` global. It isn't the path of the site, but rather the request: `stripslashes( $_SERVER['REQUEST_URI'] )`
* I'm reluctant to switch `$blogname` & `$blog_title`. I doubt they would cause any harm, it just seems superfluous.
* There are touches to the `$domain` global within `wpmu_validate_blog_signup()` & `validate_another_blog_signup()` -- boy do they seem fragile -- like neither function work reliably outside of `wp-signup.php`, otherwise the `$domain` global is always gotten from whatever `ms-settings.php` finds.

Concluding:
* I /think/ the `$domain` global can get switched to `$current_site->domain` without any problems. The only code I can find that relies on this global is related to sign-ups, and in that context I think it does make sense to switch this global.

**Comment by boonebgorges** [comment]
Thanks!

**Comment by JJJ** [comment]
This will go out in 2.1.0 (the next release.)
